version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:latest


    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-build

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test

      - save_cache:
          key: deps-build
          paths:
            - ~/repo/_build
            - ~/repo/deps
